# Generated by Django 5.2.3 on 2026-07-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
