# Generated by Django 5.1.1 on 2024-10-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_project_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='core_tech',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='supporting_tech',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Description goes here'),
        ),
    ]
