# Generated by Django 5.1.1 on 2024-10-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
